# (f) FSA

## Importing array from numpy

In [1]:
from numpy import array

## Defining a, b, c , init and final matrix from the given FSA

In [2]:
a = array([
    [0, 0, 0, 1],
    [0, 0, 0, 1],
    [0, 0, 1, 0],
    [0, 0, 0, 1]
])

In [3]:
b = array([
    [0, 1, 0 ,0],
    [0, 1, 0, 0],
    [0, 0, 0, 0],
    [0, 1, 0, 0]
])

In [4]:
c = array([
    [0, 0, 1, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0]
])

In [5]:
init = array([
    [1, 0, 0, 0]
])

In [6]:
final = array([
    [1],
    [1],
    [1],
    [0]
])

## Testing to check output

In [7]:
init.dot(b).dot(a).dot(b).dot(final)

array([[1]])

## Defining function to check possible inputs 

In [8]:
def fsa(array):
    result=init
    for i in range(len(array)):
        result=result.dot(array[i])
    result=result.dot(final)
    return result
        

## Testing different inputs... 

In [9]:
fsa([b,a,b])

array([[1]])

In [10]:
fsa([b,b,a,b])

array([[1]])

In [11]:
fsa([b,b,b,a,b])

array([[1]])

In [12]:
fsa([b,b,b,a,a,a,b])

array([[1]])

In [13]:
fsa([b,b,b,a,a,a,b,b,b,b])

array([[1]])

In [14]:
fsa([b,b,b,a,a,a,b,b,b,b,c])

array([[0]])

In [15]:
fsa([b,b,b,a,a,a,b,b,b,b,c,a])

array([[0]])

In [16]:
fsa([c,a])

array([[1]])

In [17]:
fsa([c,a,a,a,a])

array([[1]])

In [18]:
fsa([c,a,c])

array([[0]])

In [19]:
fsa([a,b,b,b])

array([[1]])

In [20]:
fsa([a,b,a,b])

array([[1]])

In [21]:
fsa([a,a,a,b,b,b,b])

array([[1]])

## Printing the resulting regex from above testing

In [22]:
print("The regular expression for the FSA is : '(b+(a+b+)*|ca*|(a+b+)+)'")

The regular expression for the FSA is : '(b+(a+b+)*|ca*|(a+b+)+)'
